sudo pacman -S albert
sudo pacman -S atom
sudo pacman -S geary
sudo pacman -S gnome-tweaks
sudo pacman -S htop
sudo pacman -S nethogs
sudo pacman -S notepadqq
sudo pacman -S python-pip
sudo pacman -S solaar
sudo pacman -S terminator
sudo pacman -S vlc